# syntax=docker/dockerfile:1
#
# Redmine container image.
# The database adapter and connection settings are chosen at runtime through
# REDMINE_DB_* environment variables (see docker/README.md), so every supported
# adapter (mysql2 / trilogy / postgresql / sqlite3 / sqlserver) is bundled here.

ARG RUBY_VERSION=3.4

FROM ruby:${RUBY_VERSION}-slim-trixie AS base
ENV RAILS_ENV=production \
    RAILS_LOG_TO_STDOUT=true \
    BUNDLE_WITHOUT="development:test" \
    BUNDLE_JOBS=4 \
    LANG=C.UTF-8
WORKDIR /usr/src/redmine

# ---------------------------------------------------------------------------
# Build stage: compile gems with native extensions for every DB adapter.
# ---------------------------------------------------------------------------
FROM base AS build
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential pkg-config git \
      libyaml-dev libssl-dev \
      libpq-dev libmariadb-dev libsqlite3-dev freetds-dev \
 && rm -rf /var/lib/apt/lists/*

COPY Gemfile ./
COPY docker/Gemfile.local ./Gemfile.local
# Placeholder so the Gemfile does not warn about a missing database.yml.
# The first line is the marker the entrypoint looks for before it replaces the
# file with one generated from REDMINE_DB_* at container start.
RUN mkdir -p config \
 && printf '# Generated by redmine-entrypoint (build-time placeholder, replaced at startup)\nproduction:\n  adapter: sqlite3\n  database: sqlite/redmine.sqlite3\n' > config/database.yml
RUN bundle install \
 && rm -rf /usr/local/bundle/cache/*.gem \
 && find /usr/local/bundle/gems -name '*.o' -delete

# ---------------------------------------------------------------------------
# Runtime stage
# ---------------------------------------------------------------------------
FROM base AS runtime
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates curl gosu tzdata libyaml-0-2 \
      libpq5 libmariadb3 libsqlite3-0 libsybdb5 freetds-common \
      imagemagick ghostscript git subversion \
 && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 1000 redmine \
 && useradd --uid 1000 --gid redmine --create-home --home-dir /home/redmine --shell /usr/sbin/nologin redmine

COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --chown=redmine:redmine . .
COPY --from=build --chown=redmine:redmine /usr/src/redmine/Gemfile.lock /usr/src/redmine/config/database.yml ./
RUN mv database.yml config/database.yml
COPY --chown=redmine:redmine docker/Gemfile.local ./Gemfile.local
COPY --chown=redmine:redmine docker/puma.rb ./config/puma.rb
COPY --chown=redmine:redmine docker/config.ru ./config.ru
COPY docker/entrypoint.sh /usr/local/bin/redmine-entrypoint

RUN chmod 0755 /usr/local/bin/redmine-entrypoint \
 && mkdir -p files sqlite log tmp/pids tmp/cache tmp/sessions tmp/thumbnails tmp/pdf \
              public/assets public/plugin_assets plugins themes \
 && chown -R redmine:redmine files sqlite log tmp public/assets public/plugin_assets plugins themes config

VOLUME ["/usr/src/redmine/files", "/usr/src/redmine/sqlite"]
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=180s --retries=3 \
  CMD curl -fsS "http://127.0.0.1:${PORT:-3000}${RAILS_RELATIVE_URL_ROOT:-}/" > /dev/null || exit 1

ENTRYPOINT ["redmine-entrypoint"]
CMD ["rails", "server", "-b", "0.0.0.0"]
