#!/usr/bin/env bash
#
# Entrypoint for the Redmine container image.
#
#  1. Resolve *_FILE secrets into their plain variables.
#  2. Generate config/database.yml from REDMINE_DB_* (or use REDMINE_DATABASE_YML).
#  3. Generate config/configuration.yml from REDMINE_SMTP_* / attachments settings
#     (or use REDMINE_CONFIGURATION_YML).
#  4. Provide SECRET_KEY_BASE (generated once and persisted when not given).
#  5. Wait for the database, run migrations and load default data.
#  6. Drop privileges and exec the command.
#
# Every variable is documented in docker/README.md.

set -Eeuo pipefail

REDMINE_ROOT=/usr/src/redmine
cd "$REDMINE_ROOT"

GENERATED_MARK='# Generated by redmine-entrypoint'

log()  { printf '[redmine-entrypoint] %s\n' "$*" >&2; }
die()  { log "ERROR: $*"; exit 1; }

is_true() {
  case "${1,,}" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

# file_env VAR [DEFAULT]: honour VAR_FILE (Docker secrets). VAR and VAR_FILE are exclusive.
file_env() {
  local var="$1" file_var="${1}_FILE" default="${2:-}" value
  if [ -n "${!var:-}" ] && [ -n "${!file_var:-}" ]; then
    die "both $var and $file_var are set, but they are exclusive"
  fi
  if [ -n "${!var:-}" ]; then
    value="${!var}"
  elif [ -n "${!file_var:-}" ]; then
    [ -r "${!file_var}" ] || die "$file_var points to an unreadable file: ${!file_var}"
    value="$(< "${!file_var}")"
  else
    value="$default"
  fi
  export "$var"="$value"
  unset "$file_var"
}

# yaml_str VALUE: emit VALUE as a double-quoted YAML scalar.
yaml_str() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

# yaml_int NAME VALUE: validate an integer option.
yaml_int() {
  [[ "$2" =~ ^[0-9]+$ ]] || die "$1 must be an integer, got: $2"
  printf '%s' "$2"
}

# yaml_bool NAME VALUE: normalise a boolean option.
yaml_bool() {
  if is_true "$2"; then printf 'true'; else
    case "${2,,}" in
      0|false|no|off) printf 'false' ;;
      *) die "$1 must be true or false, got: $2" ;;
    esac
  fi
}

# user_owned FILE: true when FILE exists and was not generated by this script.
user_owned() {
  [ -e "$1" ] && ! head -n1 "$1" 2>/dev/null | grep -qF "$GENERATED_MARK"
}

running_as_root() { [ "$(id -u)" = '0' ]; }

# run_as_redmine CMD...: run CMD as the redmine user when we are root.
run_as_redmine() {
  if running_as_root; then
    gosu redmine "$@"
  else
    "$@"
  fi
}

# ---------------------------------------------------------------------------
# 1. Secrets from files
# ---------------------------------------------------------------------------
file_env REDMINE_DB_PASSWORD
file_env REDMINE_SMTP_PASSWORD

# ---------------------------------------------------------------------------
# 2. config/database.yml
# ---------------------------------------------------------------------------
RAILS_ENV="${RAILS_ENV:-production}"
export RAILS_ENV

DB_ADAPTER="${REDMINE_DB_ADAPTER:-sqlite3}"
case "${DB_ADAPTER,,}" in
  sqlite3|sqlite)        DB_ADAPTER=sqlite3 ;;
  mysql2|mysql)          DB_ADAPTER=mysql2 ;;
  trilogy)               DB_ADAPTER=trilogy ;;
  postgresql|postgres|pg) DB_ADAPTER=postgresql ;;
  sqlserver|mssql)       DB_ADAPTER=sqlserver ;;
  *) die "unsupported REDMINE_DB_ADAPTER '$DB_ADAPTER' (use mysql2, trilogy, postgresql, sqlite3 or sqlserver)" ;;
esac

case "$DB_ADAPTER" in
  mysql2|trilogy) DB_DEFAULT_PORT=3306; DB_DEFAULT_ENCODING=utf8mb4 ;;
  postgresql)     DB_DEFAULT_PORT=5432; DB_DEFAULT_ENCODING=unicode ;;
  sqlserver)      DB_DEFAULT_PORT=1433; DB_DEFAULT_ENCODING= ;;
  sqlite3)        DB_DEFAULT_PORT=;     DB_DEFAULT_ENCODING= ;;
esac

DB_HOST="${REDMINE_DB_HOST:-localhost}"
DB_PORT="${REDMINE_DB_PORT:-$DB_DEFAULT_PORT}"
DB_USERNAME="${REDMINE_DB_USERNAME:-redmine}"
DB_PASSWORD="${REDMINE_DB_PASSWORD:-}"
DB_ENCODING="${REDMINE_DB_ENCODING:-$DB_DEFAULT_ENCODING}"
DB_POOL="${REDMINE_DB_POOL:-${RAILS_MAX_THREADS:-5}}"
if [ "$DB_ADAPTER" = sqlite3 ]; then
  DB_DATABASE="${REDMINE_DB_DATABASE:-$REDMINE_ROOT/sqlite/redmine.sqlite3}"
else
  DB_DATABASE="${REDMINE_DB_DATABASE:-redmine}"
fi

write_database_yml() {
  local target=config/database.yml
  {
    echo "$GENERATED_MARK from REDMINE_DB_* environment variables. Do not edit; set REDMINE_DATABASE_YML to supply your own file."
    echo "${RAILS_ENV}:"
    echo "  adapter: $DB_ADAPTER"
    if [ "$DB_ADAPTER" = sqlite3 ]; then
      echo "  database: $(yaml_str "$DB_DATABASE")"
    else
      echo "  host: $(yaml_str "$DB_HOST")"
      echo "  port: $(yaml_int REDMINE_DB_PORT "$DB_PORT")"
      echo "  database: $(yaml_str "$DB_DATABASE")"
      echo "  username: $(yaml_str "$DB_USERNAME")"
      echo "  password: $(yaml_str "$DB_PASSWORD")"
      [ -n "$DB_ENCODING" ] && echo "  encoding: $(yaml_str "$DB_ENCODING")"
    fi
    echo "  pool: $(yaml_int REDMINE_DB_POOL "$DB_POOL")"
    case "$DB_ADAPTER" in
      mysql2|trilogy)
        [ -n "${REDMINE_DB_SSLMODE:-}" ] && echo "  ssl_mode: $(yaml_str "$REDMINE_DB_SSLMODE")"
        echo "  variables:"
        echo "    transaction_isolation: $(yaml_str "${REDMINE_DB_TRANSACTION_ISOLATION:-READ-COMMITTED}")"
        ;;
      postgresql)
        [ -n "${REDMINE_DB_SSLMODE:-}" ] && echo "  sslmode: $(yaml_str "$REDMINE_DB_SSLMODE")"
        ;;
      sqlserver)
        echo "  encrypt: $(yaml_bool REDMINE_DB_ENCRYPT "${REDMINE_DB_ENCRYPT:-false}")"
        echo "  tds_version: $(yaml_str "${REDMINE_DB_TDS_VERSION:-7.3}")"
        if is_true "${REDMINE_DB_AZURE:-false}"; then echo "  azure: true"; fi
        ;;
    esac
    [ -n "${REDMINE_DB_TIMEOUT:-}" ] && echo "  timeout: $(yaml_int REDMINE_DB_TIMEOUT "$REDMINE_DB_TIMEOUT")"
    true
  } > "$target.tmp"
  mv "$target.tmp" "$target"
  chmod 0640 "$target"
}

if [ -n "${REDMINE_DATABASE_YML:-}" ]; then
  [ -r "$REDMINE_DATABASE_YML" ] || die "REDMINE_DATABASE_YML points to an unreadable file: $REDMINE_DATABASE_YML"
  log "using database.yml from $REDMINE_DATABASE_YML"
  if [ "$REDMINE_DATABASE_YML" != "$REDMINE_ROOT/config/database.yml" ]; then
    cp "$REDMINE_DATABASE_YML" config/database.yml
  fi
elif user_owned config/database.yml; then
  log "config/database.yml exists and was not generated here; leaving it untouched"
else
  log "generating config/database.yml (adapter=$DB_ADAPTER, env=$RAILS_ENV)"
  write_database_yml
fi

# ---------------------------------------------------------------------------
# 3. config/configuration.yml
# ---------------------------------------------------------------------------
ATTACHMENTS_PATH="${REDMINE_ATTACHMENTS_STORAGE_PATH:-$REDMINE_ROOT/files}"

write_configuration_yml() {
  local target=config/configuration.yml
  {
    echo "$GENERATED_MARK from REDMINE_SMTP_* / REDMINE_ATTACHMENTS_STORAGE_PATH. Do not edit; set REDMINE_CONFIGURATION_YML to supply your own file."
    echo "default:"
    echo "  attachments_storage_path: $(yaml_str "$ATTACHMENTS_PATH")"
    if [ -n "${REDMINE_SMTP_ADDRESS:-}" ]; then
      echo "  email_delivery:"
      echo "    delivery_method: :smtp"
      echo "    smtp_settings:"
      echo "      address: $(yaml_str "$REDMINE_SMTP_ADDRESS")"
      echo "      port: $(yaml_int REDMINE_SMTP_PORT "${REDMINE_SMTP_PORT:-587}")"
      [ -n "${REDMINE_SMTP_DOMAIN:-}" ] && echo "      domain: $(yaml_str "$REDMINE_SMTP_DOMAIN")"
      if [ -n "${REDMINE_SMTP_USER_NAME:-}" ]; then
        echo "      authentication: :${REDMINE_SMTP_AUTHENTICATION:-plain}"
        echo "      user_name: $(yaml_str "$REDMINE_SMTP_USER_NAME")"
        echo "      password: $(yaml_str "${REDMINE_SMTP_PASSWORD:-}")"
      fi
      echo "      enable_starttls_auto: $(yaml_bool REDMINE_SMTP_ENABLE_STARTTLS_AUTO "${REDMINE_SMTP_ENABLE_STARTTLS_AUTO:-true}")"
      echo "      openssl_verify_mode: $(yaml_str "${REDMINE_SMTP_OPENSSL_VERIFY_MODE:-peer}")"
    fi
  } > "$target.tmp"
  mv "$target.tmp" "$target"
  chmod 0640 "$target"
}

if [ -n "${REDMINE_CONFIGURATION_YML:-}" ]; then
  [ -r "$REDMINE_CONFIGURATION_YML" ] || die "REDMINE_CONFIGURATION_YML points to an unreadable file: $REDMINE_CONFIGURATION_YML"
  log "using configuration.yml from $REDMINE_CONFIGURATION_YML"
  if [ "$REDMINE_CONFIGURATION_YML" != "$REDMINE_ROOT/config/configuration.yml" ]; then
    cp "$REDMINE_CONFIGURATION_YML" config/configuration.yml
  fi
elif user_owned config/configuration.yml; then
  log "config/configuration.yml exists and was not generated here; leaving it untouched"
else
  log "generating config/configuration.yml"
  write_configuration_yml
fi

# ---------------------------------------------------------------------------
# 4. SECRET_KEY_BASE
# ---------------------------------------------------------------------------
mkdir -p "$ATTACHMENTS_PATH" sqlite log tmp/pids tmp/cache tmp/sessions tmp/thumbnails tmp/pdf public/assets public/plugin_assets

if [ -z "${SECRET_KEY_BASE:-}" ]; then
  SECRET_FILE="${SECRET_KEY_BASE_FILE:-$ATTACHMENTS_PATH/.secret_key_base}"
  if [ ! -s "$SECRET_FILE" ]; then
    log "SECRET_KEY_BASE not set; generating one into $SECRET_FILE (keep this file, or set SECRET_KEY_BASE)"
    mkdir -p "$(dirname "$SECRET_FILE")"
    (umask 077; ruby -rsecurerandom -e 'print SecureRandom.hex(64)' > "$SECRET_FILE")
  fi
  SECRET_KEY_BASE="$(< "$SECRET_FILE")"
  export SECRET_KEY_BASE
fi

# ---------------------------------------------------------------------------
# Ownership (only when started as root; `--user` setups skip this)
# ---------------------------------------------------------------------------
if running_as_root; then
  chown redmine:redmine "$ATTACHMENTS_PATH" sqlite
  [ -e "$ATTACHMENTS_PATH/.secret_key_base" ] && chown redmine:redmine "$ATTACHMENTS_PATH/.secret_key_base"
  chown -R redmine:redmine log tmp public/assets public/plugin_assets config/database.yml config/configuration.yml
  if [ "$DB_ADAPTER" = sqlite3 ]; then
    mkdir -p "$(dirname "$DB_DATABASE")"
    chown redmine:redmine "$(dirname "$DB_DATABASE")"
    [ -e "$DB_DATABASE" ] && chown redmine:redmine "$DB_DATABASE"
  fi
fi

rm -f tmp/pids/server.pid

# ---------------------------------------------------------------------------
# 5. Database setup (only for Rails/Rake style commands)
# ---------------------------------------------------------------------------
case "${1:-}" in
  rails|rake|bin/rails|bin/rake|puma)
    set -- bundle exec "$@"
    setup_database=true
    ;;
  bundle)
    setup_database=true
    ;;
  *)
    setup_database=false
    ;;
esac

if [ "$setup_database" = true ]; then
  # Plugins may bring their own Gemfiles.
  if compgen -G "plugins/*/Gemfile" > /dev/null || compgen -G "plugins/*/PluginGemfile" > /dev/null; then
    if ! bundle check > /dev/null 2>&1; then
      log "installing plugin gems"
      bundle install
    fi
  fi

  deadline=$(( SECONDS + ${REDMINE_DB_WAIT_TIMEOUT:-60} ))

  if [ "$DB_ADAPTER" != sqlite3 ]; then
    log "waiting for $DB_HOST:$DB_PORT"
    until (exec 3<>"/dev/tcp/$DB_HOST/$DB_PORT") 2>/dev/null; do
      (( SECONDS < deadline )) || die "database $DB_HOST:$DB_PORT is not reachable after ${REDMINE_DB_WAIT_TIMEOUT:-60}s"
      sleep 2
    done
  fi

  if ! is_true "${REDMINE_SKIP_DB_MIGRATE:-false}"; then
    log "running db:prepare (create if missing, then migrate)"
    until run_as_redmine bundle exec rake db:prepare; do
      (( SECONDS < deadline )) || die "db:prepare keeps failing; see the errors above"
      log "db:prepare failed, retrying in 5s"
      sleep 5
    done
    if is_true "${REDMINE_PLUGINS_MIGRATE:-true}" && compgen -G "plugins/*/init.rb" > /dev/null; then
      log "running redmine:plugins:migrate"
      run_as_redmine bundle exec rake redmine:plugins:migrate
    fi
  else
    log "REDMINE_SKIP_DB_MIGRATE is set; skipping migrations"
  fi

  if is_true "${REDMINE_LOAD_DEFAULT_DATA:-true}"; then
    log "loading default data (REDMINE_LANG=${REDMINE_LANG:-en}) unless already present"
    REDMINE_LANG="${REDMINE_LANG:-en}" run_as_redmine bundle exec rake redmine:load_default_data
  fi
fi

# ---------------------------------------------------------------------------
# 6. Exec
# ---------------------------------------------------------------------------
log "starting: $*"
if running_as_root; then
  exec gosu redmine "$@"
else
  exec "$@"
fi
